PL/SQL Developer Test script 3.0
18
-- CREATED ON 16/10/2021 BY DANIEL.NATAN 
DECLARE 
  V_IMC NUMBER;
  V_PS_PESSOA NUMBER;
  V_NR_ALTURA NUMBER;
BEGIN
  V_PS_PESSOA := 87.52;
  V_NR_ALTURA := 1.45;
  
  V_IMC := V_NR_ALTURA * V_NR_ALTURA;
  /*V_IMC = 2.1025*/
  V_IMC := ROUND(V_PS_PESSOA / V_IMC,2);
  
  DBMS_OUTPUT.PUT_LINE(V_IMC);
  
  V_IMC := V_PS_PESSOA / (V_NR_ALTURA * V_NR_ALTURA);
  DBMS_OUTPUT.PUT_LINE(V_IMC);
END;
0
0
