PL/SQL Developer Test script 3.0
17
-- CREATED ON 16/10/2021 BY DANIEL.NATAN 
DECLARE 
  V_NR_UM NUMBER;
  V_NR_DOIS NUMBER;
  V_NR_RESULTADO NUMBER;
  V_DS_RESULTADO VARCHAR2(50);
BEGIN
  V_NR_UM := 4;
  V_NR_DOIS := 3;
  V_NR_RESULTADO := V_NR_UM + V_NR_DOIS;
  
  --O RESULTADO DA SOMA DE 4 + 3 É IGUAL A 7
  V_DS_RESULTADO := 'O RESULTADO DA SOMA DE '||V_NR_UM||' + '||V_NR_DOIS
                    ||' É IGUAL A '||V_NR_RESULTADO;
  
  DBMS_OUTPUT.PUT_LINE(V_DS_RESULTADO);
END;
0
0
