CREATE TABLE COMBUSTIVEL(
  CD_COMBUSTIVEL NUMBER(10),
  DS_COMBUSTIVEL VARCHAR2(60),
  VL_COMBUSTIVEL NUMBER(15,2),
  DT_RECORD      DATE,
  DT_REFRESH     DATE,
  CONSTRAINT PKCOMBUSTIVEL PRIMARY KEY (CD_COMBUSTIVEL)
);

CREATE TABLE PROPRIETARIO(
  CD_PROPRIETARIO NUMBER(10),
  NM_PROPRIETARIO VARCHAR2(100),
  NR_CNPJCPF      VARCHAR2(14),
  DS_ENDERECO     VARCHAR2(200),
  NR_TELEFONE     NUMBER(11),
  DT_RECORD       DATE,
  DT_REFRESH      DATE,
  CONSTRAINT PKPROPRIETARIO PRIMARY KEY (CD_PROPRIETARIO)
);

CREATE TABLE VEICULO(
  NR_PLACA         VARCHAR2(7),
  CD_COMBUSTIVEL   NUMBER(10),
  CD_PROPRIETARIO  NUMBER(10),
  KM_ATUAL         NUMBER(10),
  DT_RECORD        DATE,
  DT_REFRESH       DATE,
  CONSTRAINT PKVEICULO PRIMARY KEY (NR_PLACA),
  CONSTRAINT RVEICULO_COMBUSTIVEL FOREIGN KEY (CD_COMBUSTIVEL)
                REFERENCES COMBUSTIVEL(CD_COMBUSTIVEL),
  CONSTRAINT RVEICULO_PROPRIETARIO FOREIGN KEY (CD_PROPRIETARIO)
                REFERENCES PROPRIETARIO(CD_PROPRIETARIO)
);

CREATE TABLE FRENTISTA(
  CD_FRENTISTA  NUMBER(10),
  NM_FRENTISTA  VARCHAR2(100),
  PC_COMISSAO   NUMBER(4,2),
  DT_RECORD     DATE,
  DT_REFRESH    DATE,
  CONSTRAINT PKFRENTISTA PRIMARY KEY (CD_FRENTISTA)
);

CREATE TABLE ABASTECIMENTO(
  CD_ABASTECIMENTO   NUMBER(15),
  NR_PLACA           VARCHAR2(7),
  CD_FRENTISTA       NUMBER(10),
  QT_ABASTECIDA      NUMBER(6,3),
  KM_ABASTECIMENTO   NUMBER(10),
  VL_COMBUSTIVEL     NUMBER(15,2),
  DT_RECORD          DATE,
  DT_REFRESH         DATE,
  CONSTRAINT PKABASTECIMENTO PRIMARY KEY (CD_ABASTECIMENTO),
  CONSTRAINT RABASTECIMENTO_VEICULO FOREIGN KEY (NR_PLACA)
               REFERENCES VEICULO(NR_PLACA),
  CONSTRAINT RABASTECIMENTO_FRENTISTA FOREIGN KEY (CD_FRENTISTA)
               REFERENCES FRENTISTA(CD_FRENTISTA)
);
