CREATE TABLE PESSOA (
  NM_PESSOA  VARCHAR2(100),
  NR_CPF VARCHAR2(11),
  DT_NASCIMENTO DATE,
  ID_PESSOA NUMBER(15),
  NR_ALTURA NUMBER(8,2)
);

SELECT *
  FROM PESSOA;
  
INSERT INTO PESSOA(
  NM_PESSOA,
  NR_CPF,
  DT_NASCIMENTO,
  ID_PESSOA,
  NR_ALTURA)
VALUES(
  'FLORISBALDO SILVEIRA',
  '12312312312',
  '15/07/1921',
  2,
  1.48);
  
SELECT * FROM PESSOA;

UPDATE PESSOA
   SET DT_NASCIMENTO = '15/07/1971',
       NR_ALTURA = 1.65
 WHERE ID_PESSOA = 2;
 
DELETE PESSOA
 WHERE ID_PESSOA = 1;

DROP TABLE PESSOA;
