CRIE UMA TABELA PARA ARMAZENAR INFORMAÇÕES DE CARROS, ESSA TABELA 
PRECISA TER, A PLACA DO VEÍCULO, DESCRIÇÃO DO MODELO, DATA DE COMPRA,
VALOR DE VENDA, ANO DO MODELO

ALTER TABLE CARRO MODIFY( NR_PLACA VARCHAR2(7));

CREATE TABLE CARRO(
  NR_PLACA VARCHAR2(7),
  DS_MODELO VARCHAR2(100),
  DT_COMPRA DATE,
  VL_VENDA NUMBER(15,2),
  NR_ANOMODELO NUMBER(4)
);

INSERT INTO CARRO (NR_PLACA,DS_MODELO,DT_COMPRA,VL_VENDA,NR_ANOMODELO)
  VALUES ('ABC1234','FUSCA','01/05/1995',4500.24,1990);
INSERT INTO CARRO (NR_PLACA,DS_MODELO,DT_COMPRA,VL_VENDA,NR_ANOMODELO)
  VALUES ('DNS1489','COROLLA','25/04/2020',45857.41,2019);
  
SELECT * FROM CARRO;

UPDATE CARRO
   SET VL_VENDA = 50000
 WHERE NR_PLACA = 'DNS1489';
 
DELETE 
  FROM CARRO
 WHERE NR_PLACA = 'ABC1234';
 
DROP TABLE CARRO;
