CRIE UMA TABELA NOTAFISCAL QUE VAI TER, NUMERO DA NOTA, VALOR DA NOTA,
DESCRIÇÃO DO VENDEDOR, DESCRIÇÃO DO CLIENTE, DATA DE COMPRA.

CRIE UMA TABELA ITEMNOTA QUE VAI TER UM ID DO ITEM, VALOR DO ITEM, 
DESCRIÇÃO DO ITEM, REFERENCIAR A TABELA NOTAFISCAL

CREATE TABLE NOTAFISCAL(
  NR_NOTA NUMBER(15),
  VL_NOTA NUMBER(15,2),
  DS_VENDEDOR VARCHAR2(100),
  DS_CLIENTE VARCHAR2(100),
  DT_COMPRA DATE,
  CONSTRAINT PKNOTAFISCAL PRIMARY KEY (NR_NOTA)
);

CREATE TABLE ITEMNOTA(
  ID_ITEM NUMBER(15),
  VL_ITEM NUMBER(15,2),
  DS_ITEM VARCHAR2(100),
  NR_NOTA NUMBER(15),
  CONSTRAINT PKITEMNOTA PRIMARY KEY (ID_ITEM),
  CONSTRAINT FKITEMNOTA_NOTAFISCAL FOREIGN KEY (NR_NOTA) REFERENCES NOTAFISCAL(NR_NOTA)
);

/*
INSIRA OS DADOS DE DUAS NOTAS, E DEPOIS PARA A PRIMEIRA NOTA, INSIRA 3 ITENS.
FAÇA UMA CONSULTA TRAZENDO, OS ITENS JUNTO COM A DESCRIÇÃO DO CLIENTE
*/



